---
# DevSec Nginx Baseline: https://dev-sec.io/baselines/nginx/
# Buffer limits, timeouts, security headers, remove default site
# Run when nginx is used: ansible-playbook nginx/hardening.yml

- name: Harden nginx configuration (DevSec)
  hosts: all
  become: yes
  vars:
    nginx_user: www-data
    nginx_client_body_buffer_size: '1k'
    nginx_client_max_body_size: '1k'
    nginx_client_header_buffer_size: '1k'
    nginx_large_client_header_buffers: '2 1k'
    nginx_keepalive_timeout: '5 5'
    nginx_client_body_timeout: '10'
    nginx_client_header_timeout: '10'
    nginx_send_timeout: '10'
    nginx_limit_conn_zone: '$binary_remote_addr zone=default:10m'
    nginx_limit_conn: 'default 5'
    nginx_remove_default_site: true

  handlers:
    - name: Reload nginx
      systemd:
        name: nginx
        state: reloaded

  tasks:
    - name: Check if nginx is installed
      command: nginx -v
      register: nginx_check
      changed_when: false
      failed_when: false

    - name: Set nginx worker user (nginx-01)
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^\s*#?\s*user\s+.*'
        line: 'user {{ nginx_user }};'
        insertbefore: 'worker_processes'
      when: nginx_check.rc == 0
      notify: Reload nginx

    - name: Deploy hardening config (nginx-06, nginx-07, nginx-08, nginx-09, nginx-10, nginx-13, nginx-15, nginx-17)
      template:
        src: nginx-hardening.conf.j2
        dest: /etc/nginx/conf.d/90-hardening.conf
        owner: root
        group: root
        mode: '0644'
      when: nginx_check.rc == 0
      notify: Reload nginx

    - name: Set server_tokens off (nginx-05)
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^\s*#?\s*server_tokens\s+'
        line: '    server_tokens off;'
        insertafter: 'http {'
      when: nginx_check.rc == 0
      notify: Reload nginx

    - name: Remove default nginx site (nginx-03)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/conf.d/default.conf
      when:
        - nginx_check.rc == 0
        - nginx_remove_default_site | default(true) | bool
      notify: Reload nginx
